### ISSUE TITLE
Update RDM hooks to handle rebasing

### ISSUE THREAD

**Issue by joshuatz** [innolitics/rdm#112]
As I've been working rebasing more into my workflow lately, I couldn't help but notice that the RDM hook frequently adds the issue number multiple times (x number of rebase hits on the commit), so after a number of rebases, you can accidentally end up with:

```
commit b68eea3ee25323d4acf30dbd2f425219e0f7624a
Author: Example User <user@example.com>
Date:   Thu Sep 1 12:32:34 2022 -0700

Fix widget factory

Issue #24

Issue #24

Issue #24
```

and so on. Not a big deal, but comes up enough to warrant a solution in my opinion.

I think this should be a pretty easy fix and can probably tackle this sometime soon.

**Comment by johndgiese** [comment]
Thanks for writing up this issue!

**Comment by joshuatz** [comment]
I'm going to close this; in the time since creating this issue I have not actually been able to reproduce this again. I'm not sure what exactly changed, since I know I used to run into this occasionally, but I haven't seen it since with any combo of `rebase` or `--amend`.
