### ISSUE TITLE
Populate `requirements.yml` from GitHub API

### ISSUE THREAD

**Issue by ReeceStevens** [innolitics/rdm#3]
Use the GitHub API to construct the `requirements.yml` file and `problem-reports.yml` files. 

Both of these files should have the same format:

```
1: "description of the requirement or problem report in GitHub flavored markdown"
3: "description of the requirement or problem report in GitHub flavored markdown"
4: "description of the requirement or problem report in GitHub flavored markdown"
```

We should generate both yaml files using a new Makefile rule and a new `rdm subcommand`.

This will require:

- [ ] Developing a thin interface to the GitHub API (authentication, depagination, issues)
- [ ] Processing API responses and producing the `.yml` file

We should use an existing GitHub API library, e.g. http://pygithub.readthedocs.io/en/latest/introduction.html

**Comment by ReeceStevens** [comment]
Relevant API documentation: https://developer.github.com/v3/issues/

**Comment by johndgiese** [comment]
@ReeceStevens I added a few more details to the GitHub issue.

**Comment by ReeceStevens** [comment]
Some points of clarification as I work through this ticket:

1. Where do we want the user's GitHub information to be stored? `init/data/system.yml`? If that is the case, we cannot auto-populate `requirements.yml` and `problem_reports.yml` during the first call to `rdm init`. I don't think that's a big issue, but something worth noting. We will also need the user to have a GH access token in an environment variable or some other secure location. I assume we could also have them store a limited access token or an application-specific token in the `system.yml` file.

2. The index for the requirements is currently the order in which they are returned by the github API. This seems kind of brittle, so perhaps a better way to assign an "ID" to a requirement is to have a specific tag (kind of like how Mobius does it, with the r-number) that we can identify as a requirement ID. What do you think about this approach?

3. I don't want to design for features that don't exist yet, but I was considering moving the GitHub-specific code into a `backends` directory-- that way, depending on the specified project management software specified in `system.yml`, we can just import the correct backend and start syncing. It also emphasizes that the core functionality isn't tied to GitHub as a platform, which might be a nice thing to show off.

4. I am trying to come up with a term that encompasses both requirements and problem reports, and am struggling to find a good fit (for the `rdm <subcommand>`). The ones I'm working with so far:

- project_metadata
- project_docs
- docs (the term seems overloaded in our context so I don't feel great about it)
- requirements (doesn't cover problem reports but is the closest to concisely conveying the idea)

**Comment by ReeceStevens** [comment]
Okay, sounds good. I will look and see if we can piggyback off the ssh key... I am not entirely sure if we can or not, but it's worth a shot. Worst case scenario, setting up an access token for the GitHub API took less than 5 minutes for me-- I think we could point people to the token generation instructions if there's not a better way immediately available.

GitHub issue numbers probably would work just fine for unique IDs-- however, the YAML file probably will be a bit confusing because the requirement IDs will just be numbers, but the numbers may or may not be sequential. Not a huge issue, and we can always change it later with relatively little friction if we decide we need something more.

And good call on sticking with github for now. I like `rdm github_issues` as a subcommand.

**Comment by ReeceStevens** [comment]
After doing a bit more digging, I am pretty sure that we can't authenticate users for the github API via SSH-- you have to have an access token or pass in username/password.

**Comment by ReeceStevens** [comment]
@johndgiese this was my solution to the login issue for now: 59397c0

It checks if an API key is set, and if not, will fall back to username and password.
