### ISSUE TITLE
How do I insert name of own project in documents?

### ISSUE THREAD

**Issue by hmogensen** [innolitics/rdm#76]
A very basic question here: in some of the files in the document folder, there are some sort of tags, like this for instance:
 {{ system.project_name }}
Is there a way to specify what this tag will be replaced with in the generated release version of the document?
Or do I manually replace the above string with the name of my project, everywhere it occurs?

**Comment by johndgiese** [comment]
Good question! This should certainly be added to the documentation somewhere.

The `system` refers to the file name. In this case, `data/system.yml`. The `project_name` refers to the key in `system.yml`.

**Comment by johndgiese** [comment]
I've added some details about this to the documentation. See https://github.com/innolitics/rdm#data-files
