### ISSUE TITLE
Makefile not moving images into tmp for pdf rendering

### ISSUE THREAD

**Issue by MALathon** [innolitics/rdm#84]
Been trying to get the repo to work out of the box, had a few issues I've resolved.  I believe the issue I've found is that the tex and render commands expect images to be in tmp/images, otherwise it errors:

  'LaTeX Warning: File `./tmp/images/uimockups-ui-mockup-003.jpg' not found on input line 305.'

Probably a simple fix in the Makefile.  I'm not familiar with make scripting, but if I figure it out Ill submit a PR.

**Comment by MALathon** [comment]
OK I was wrong, the issue is with handle_images(..) function with tex.py.  As it is currently written it is not compatible with os.path, because the includegraphics LaTeX package requires all file locations to be in POSIX notation.  

I fixed it by making sure any output directory or output filenames used posixpath.join rather than os.path.join within that function.  Its sort of hacky, but I can do a PR if you'd like.

**Comment by johndgiese** [comment]
I'm actually working on this part of the codebase at this very moment. I think that pandoc is powerful enough to handle natively, and more flexibly, everything that `rdm tex` does. Thus, I'm hoping to replace `rdm tex` entirely in a new release later this week.

**Comment by johndgiese** [comment]
@MALathon I've merged in my most recent round of updates. RDM version 0.11.0 no longer includes the `rdm tex` command, but uses pandoc instead. Let me know if you have any more issues with this!
